// ─── Mock data cho Demo Mode ─────────────────────────────────────────────────
// Không gọi API, toàn bộ state lưu trong memory/sessionStorage

export const DEMO_GROUP = {
  id: 'demo',
  name: 'Đà Nẵng - Hội An 2026',
  description: 'Chuyến đi khám phá miền Trung cùng hội bạn thân',
  start_date: '2026-06-15T00:00:00Z',
  end_date: '2026-06-18T00:00:00Z',
  invite_code: 'DEMO123',
  is_public: true,
  is_ai_generating: false,
  route_destinations: 'Đà Nẵng, Hội An',
};

export const DEMO_MEMBERS = [
  { id: 1, full_name: 'Nguyễn Văn An', avatar: '', role: 'ADMIN' },
  { id: 2, full_name: 'Trần Thị Bình', avatar: '', role: 'MEMBER' },
  { id: 3, full_name: 'Lê Minh Cường', avatar: '', role: 'MEMBER' },
  { id: 4, full_name: 'Phạm Thu Dung', avatar: '', role: 'MEMBER' },
];

export const DEMO_ACTIVITIES = [
  {
    id: 1,
    name: 'Bay Hà Nội → Đà Nẵng',
    type: 'TRANSPORT',
    location: 'Sân bay Nội Bài',
    description: 'Chuyến bay VN123, khởi hành 07:00, hạ cánh 08:30.',
    start_time: '2026-06-15T00:00:00Z',
    end_time: '2026-06-15T01:30:00Z',
    status: 'APPROVED',
    estimated_cost: 1800000,
    currency: 'VND',
    lat: 21.2187,
    lng: 105.8037,
    vote_count: 4,
    has_voted: true,
    average_user_rating: 0,
    my_rating: 0,
    is_ai_generated: false,
  },
  {
    id: 2,
    name: 'Khách sạn Mường Thanh Đà Nẵng',
    type: 'HOTEL',
    location: 'Đà Nẵng',
    description: 'Check-in khách sạn 4 sao, view biển Mỹ Khê.',
    start_time: '2026-06-15T05:00:00Z',
    end_time: '2026-06-17T16:00:00Z',
    status: 'APPROVED',
    estimated_cost: 3200000,
    currency: 'VND',
    lat: 16.0544,
    lng: 108.2022,
    vote_count: 3,
    has_voted: false,
    average_user_rating: 4.5,
    my_rating: 0,
    is_ai_generated: false,
  },
  {
    id: 3,
    name: 'Tham quan Bà Nà Hills',
    type: 'ATTRACTION',
    location: 'Bà Nà Hills, Đà Nẵng',
    description: 'Cáp treo lên Bà Nà, tham quan Cầu Vàng và làng Pháp.',
    start_time: '2026-06-15T08:00:00Z',
    end_time: '2026-06-15T15:00:00Z',
    status: 'PENDING',
    estimated_cost: 750000,
    currency: 'VND',
    lat: 15.9973,
    lng: 107.9888,
    vote_count: 2,
    has_voted: false,
    average_user_rating: 0,
    my_rating: 0,
    is_ai_generated: true,
  },
  {
    id: 4,
    name: 'Ăn tối Bạch Đằng',
    type: 'RESTAURANT',
    location: 'Bạch Đằng, Đà Nẵng',
    description: 'Hải sản tươi sống, đặc sản miền Trung.',
    start_time: '2026-06-15T11:00:00Z',
    end_time: '2026-06-15T13:00:00Z',
    status: 'PENDING',
    estimated_cost: 400000,
    currency: 'VND',
    lat: 16.0678,
    lng: 108.2208,
    vote_count: 1,
    has_voted: false,
    average_user_rating: 0,
    my_rating: 0,
    is_ai_generated: false,
  },
  {
    id: 5,
    name: 'Phố cổ Hội An',
    type: 'ATTRACTION',
    location: 'Hội An, Quảng Nam',
    description: 'Dạo phố đèn lồng, thăm chùa Cầu và mua sắm.',
    start_time: '2026-06-16T02:00:00Z',
    end_time: '2026-06-16T09:00:00Z',
    status: 'PENDING',
    estimated_cost: 200000,
    currency: 'VND',
    lat: 15.8801,
    lng: 108.338,
    vote_count: 4,
    has_voted: true,
    average_user_rating: 5,
    my_rating: 5,
    is_ai_generated: false,
  },
  {
    id: 6,
    name: 'Biển Mỹ Khê',
    type: 'ATTRACTION',
    location: 'Mỹ Khê, Đà Nẵng',
    description: 'Tắm biển buổi sáng, thuê dù và ghế nằm.',
    start_time: '2026-06-17T01:00:00Z',
    end_time: '2026-06-17T05:00:00Z',
    status: 'PENDING',
    estimated_cost: 100000,
    currency: 'VND',
    lat: 16.0471,
    lng: 108.2479,
    vote_count: 3,
    has_voted: false,
    average_user_rating: 0,
    my_rating: 0,
    is_ai_generated: false,
  },
];

export const DEMO_EXPENSES = [
  {
    id: 1,
    description: 'Vé máy bay khứ hồi x4',
    amount: 7200000,
    currency: 'VND',
    paid_by: 1,
    paid_by_name: 'Nguyễn Văn An',
    split_among: [1, 2, 3, 4],
    created_at: '2026-06-10T10:00:00Z',
  },
  {
    id: 2,
    description: 'Khách sạn 3 đêm',
    amount: 3200000,
    currency: 'VND',
    paid_by: 2,
    paid_by_name: 'Trần Thị Bình',
    split_among: [1, 2, 3, 4],
    created_at: '2026-06-10T11:00:00Z',
  },
  {
    id: 3,
    description: 'Vé Bà Nà Hills x4',
    amount: 3000000,
    currency: 'VND',
    paid_by: 3,
    paid_by_name: 'Lê Minh Cường',
    split_among: [1, 2, 3, 4],
    created_at: '2026-06-15T09:00:00Z',
  },
];

export const DEMO_CHECKLIST = [
  { id: 1, title: 'Đặt vé máy bay', is_completed: true, category: 'Đồ dùng chung', assignee: { id: 1, full_name: 'Nguyễn Văn An', avatar: '' }, completed_by: { full_name: 'Nguyễn Văn An' } },
  { id: 2, title: 'Đặt khách sạn', is_completed: true, category: 'Đồ dùng chung', assignee: { id: 2, full_name: 'Trần Thị Bình', avatar: '' }, completed_by: { full_name: 'Trần Thị Bình' } },
  { id: 3, title: 'Mua kem chống nắng', is_completed: false, category: 'Đồ dùng chung', assignee: null, completed_by: null },
  { id: 4, title: 'Chuẩn bị đồ bơi', is_completed: false, category: 'Đồ dùng chung', assignee: { id: 3, full_name: 'Lê Minh Cường', avatar: '' }, completed_by: null },
  { id: 5, title: 'Đổi tiền mặt', is_completed: false, category: 'Đồ dùng chung', assignee: null, completed_by: null },
  { id: 6, title: 'Tải bản đồ offline', is_completed: true, category: 'Đồ dùng chung', assignee: { id: 4, full_name: 'Phạm Thu Dung', avatar: '' }, completed_by: { full_name: 'Phạm Thu Dung' } },
  { id: 7, title: 'Đặt tour Bà Nà Hills', is_completed: false, category: 'Ăn uống & Vui chơi', assignee: null, completed_by: null },
  { id: 8, title: 'Book nhà hàng hải sản', is_completed: false, category: 'Ăn uống & Vui chơi', assignee: { id: 2, full_name: 'Trần Thị Bình', avatar: '' }, completed_by: null },
];

export const DEMO_TOUR_STEPS = [
  {
    element: '#demo-header',
    popover: {
      title: '🗺️ Thông tin chuyến đi',
      description: 'Đây là header chuyến đi — tên, ngày đi, thành viên và nút xuất lịch trình.',
      side: 'bottom' as const,
    },
  },
  {
    element: '#demo-nav',
    popover: {
      title: '📑 Các tab chức năng',
      description: 'TripSync có 5 tab: Tổng quan, Lịch trình, Chi phí, Chuẩn bị và Tài liệu.',
      side: 'bottom' as const,
    },
  },
  {
    element: '#demo-day-selector',
    popover: {
      title: '📅 Chọn ngày',
      description: 'Chọn ngày để xem lịch trình của từng ngày trong chuyến đi.',
      side: 'bottom' as const,
    },
  },
  {
    element: '#demo-timeline',
    popover: {
      title: '⏱️ Timeline hoạt động',
      description: 'Danh sách hoạt động theo giờ. Bạn có thể đề xuất, bỏ phiếu và chốt hoạt động.',
      side: 'top' as const,
    },
  },
  {
    element: '#demo-add-btn',
    popover: {
      title: '➕ Đề xuất hoạt động',
      description: 'Thêm địa điểm, nhà hàng, khách sạn... vào lịch trình để cả nhóm bỏ phiếu.',
      side: 'bottom' as const,
    },
  },
  {
    element: '#demo-map',
    popover: {
      title: '🗺️ Bản đồ tương tác',
      description: 'Xem tất cả địa điểm trong ngày trên bản đồ, giúp tối ưu lộ trình di chuyển.',
      side: 'left' as const,
    },
  },
];
