// ===== GROUP DETAIL =====
export const FETCH_GROUP_DETAIL_REQUEST = 'FETCH_GROUP_DETAIL_REQUEST';
export const FETCH_GROUP_DETAIL_SUCCESS = 'FETCH_GROUP_DETAIL_SUCCESS';
export const FETCH_GROUP_DETAIL_FAILURE = 'FETCH_GROUP_DETAIL_FAILURE';

// ===== ACTIVITIES =====
export const FETCH_ACTIVITIES_REQUEST = 'FETCH_ACTIVITIES_REQUEST';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_FAILURE';

export const VOTE_ACTIVITY_REQUEST = 'VOTE_ACTIVITY_REQUEST';
export const VOTE_ACTIVITY_SUCCESS = 'VOTE_ACTIVITY_SUCCESS';
export const VOTE_ACTIVITY_FAILURE = 'VOTE_ACTIVITY_FAILURE';

export const FINALIZE_ACTIVITY_REQUEST = 'FINALIZE_ACTIVITY_REQUEST';
export const FINALIZE_ACTIVITY_SUCCESS = 'FINALIZE_ACTIVITY_SUCCESS';
export const FINALIZE_ACTIVITY_FAILURE = 'FINALIZE_ACTIVITY_FAILURE';

export const ADD_ACTIVITY_REQUEST = 'ADD_ACTIVITY_REQUEST';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_FAILURE = 'ADD_ACTIVITY_FAILURE';

export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAILURE = 'UPDATE_ACTIVITY_FAILURE';

export const DELETE_ACTIVITY_REQUEST = 'DELETE_ACTIVITY_REQUEST';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_FAILURE = 'DELETE_ACTIVITY_FAILURE';

export const REGENERATE_AI_REQUEST = 'REGENERATE_AI_REQUEST';
export const REGENERATE_AI_SUCCESS = 'REGENERATE_AI_SUCCESS';
export const REGENERATE_AI_FAILURE = 'REGENERATE_AI_FAILURE';

// ===== EXPENSES =====
export const GET_DEBTS_REQUEST = 'GET_DEBTS_REQUEST';
export const GET_DEBTS_SUCCESS = 'GET_DEBTS_SUCCESS';
export const GET_DEBTS_FAILURE = 'GET_DEBTS_FAILURE';

export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

export const GET_EXPENSE_SUMMARY_REQUEST = 'GET_EXPENSE_SUMMARY_REQUEST';
export const GET_EXPENSE_SUMMARY_SUCCESS = 'GET_EXPENSE_SUMMARY_SUCCESS';
export const GET_EXPENSE_SUMMARY_FAILURE = 'GET_EXPENSE_SUMMARY_FAILURE';

export const SETTLE_DEBT_REQUEST = 'SETTLE_DEBT_REQUEST';
export const SETTLE_DEBT_SUCCESS = 'SETTLE_DEBT_SUCCESS';
export const SETTLE_DEBT_FAILURE = 'SETTLE_DEBT_FAILURE';

export const GET_EXPENSE_LIST_REQUEST = 'GET_EXPENSE_LIST_REQUEST';
export const GET_EXPENSE_LIST_SUCCESS = 'GET_EXPENSE_LIST_SUCCESS';
export const GET_EXPENSE_LIST_FAILURE = 'GET_EXPENSE_LIST_FAILURE';

// ==========================================
// CHECKLIST TYPES
// ==========================================
export const GET_CHECKLIST_REQUEST = 'GET_CHECKLIST_REQUEST';
export const GET_CHECKLIST_SUCCESS = 'GET_CHECKLIST_SUCCESS';
export const GET_CHECKLIST_FAILURE = 'GET_CHECKLIST_FAILURE';

export const CREATE_CHECKLIST_REQUEST = 'CREATE_CHECKLIST_REQUEST';
export const CREATE_CHECKLIST_SUCCESS = 'CREATE_CHECKLIST_SUCCESS';
export const CREATE_CHECKLIST_FAILURE = 'CREATE_CHECKLIST_FAILURE';

export const TOGGLE_CHECKLIST_REQUEST = 'TOGGLE_CHECKLIST_REQUEST';
export const TOGGLE_CHECKLIST_SUCCESS = 'TOGGLE_CHECKLIST_SUCCESS';
export const TOGGLE_CHECKLIST_FAILURE = 'TOGGLE_CHECKLIST_FAILURE';

export const ASSIGN_CHECKLIST_REQUEST = 'ASSIGN_CHECKLIST_REQUEST';
export const ASSIGN_CHECKLIST_SUCCESS = 'ASSIGN_CHECKLIST_SUCCESS';
export const ASSIGN_CHECKLIST_FAILURE = 'ASSIGN_CHECKLIST_FAILURE';

export const DELETE_CHECKLIST_REQUEST = 'DELETE_CHECKLIST_REQUEST';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAILURE = 'DELETE_CHECKLIST_FAILURE';

// ===== ACTIVITY RATING =====
export const RATE_ACTIVITY_REQUEST = 'RATE_ACTIVITY_REQUEST';
export const RATE_ACTIVITY_SUCCESS = 'RATE_ACTIVITY_SUCCESS';
export const RATE_ACTIVITY_FAILURE = 'RATE_ACTIVITY_FAILURE';

// ===== ACTIVITY SUGGESTIONS =====
export const FETCH_SUGGESTIONS_REQUEST = 'FETCH_SUGGESTIONS_REQUEST';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_FAILURE = 'FETCH_SUGGESTIONS_FAILURE';
